---
language: python
python: "2.7"

env:
  - ANSIBLE_BASE_CMD="ansible-playbook -vvvv -l localhost -i tests/hosts tests/test.yml"

before_install:
  # update packages
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - "$ANSIBLE_BASE_CMD --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "$ANSIBLE_BASE_CMD --connection=local"

  # Run the role/playbook again, checking to make sure it's idempotent.
  # TODO: this idempotency check is failing, returning "changed"
  # for the dotfiles repo clone, and also for the symlink deploy
#  - >
#    $ANSIBLE_BASE_CMD --connection=local
#    | grep -q 'changed=0.*failed=0'
#    && (echo 'Idempotence test: pass' && exit 0)
#    || (echo 'Idempotence test: fail' && exit 1)
