---
- name: Ensure github.com is a known host.
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
  sudo: yes
  sudo_user: "{{ username }}"

- name: Install homeshick
  git:
    repo: git://github.com/andsens/homeshick.git
    dest: "{{ ansible_env.HOME }}/.homesick/repos/homeshick"

- name: Update bashrc to have homeshick initialization
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    line: 'source "$HOME/.homesick/repos/homeshick/homeshick.sh"'
    regexp: 'homeshick'
    create: yes

- name: Clone dotfiles repo.
  git:
    repo: "{{ dotfiles_repo_url_https }}"
    dest: "{{ ansible_env.HOME }}/.homesick/repos/dotfiles"
  register: clone_dotfiles_result

- name: Convert dotfiles repo origin format from HTTPS to SSH.
  command: git remote set-url origin {{ dotfiles_repo_url_ssh }}
  when: clone_dotfiles_result.changed

- name: Create symlinks for dotfiles.
  command: "{{ ansible_env.HOME}}/.homesick/repos/homeshick/bin/homeshick link dotfiles -f -q"
  when: clone_dotfiles_result.changed

- name: Install Vundle.
  git:
    repo: https://github.com/VundleVim/Vundle.vim
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

- name: Install VimPlug.
  git:
    repo: https://github.com/VundleVim/Vundle.vim
    dest: "{{ ansible_env.HOME }}/.vim/bundle/Vundle.vim"

- name: Install vim plugins.
  # Vundle command
  # command: vim +PluginInstall +qall
  # VimPlug command
  command: vim +PlugInstall +qall
  when: clone_dotfiles_result.changed

  # Haven't found a way to clean unwanted plugins
  # noninteractively.
#- name: clean vim plugins
#  command: vim +PluginClean
