---
- name: deploy dotfiles
  synchronize:
    mode: push
    src: home/
    dest: /home/{{ username }}/
    # Override Ansible's choice of "sudo rsync" below:
    rsync_path: rsync
  tags:
    - dotfiles

- name: install vundle
  git:
    repo: https://github.com/gmarik/Vundle.vim.git
    dest: /home/{{ username }}/.vim/bundle/Vundle.vim
  tags:
    - dotfiles

- name: install vim plugins
  command: vim +PluginInstall +qall
  tags:
    - dotfiles

  # Haven't found a way to clean unwanted plugins
  # noninteractively.
#- name: clean vim plugins
#  command: vim +PluginClean
