---
# Installs packages that require X, so inapproriate
# for headless server environments. See defaults/main.yml
# to override these settings.

- name: Include OS-specific vars.
  include_vars: "{{ ansible_distribution }}.yml"

- name: Add PPA for Firefox Developer Edition.
  apt_repository:
    repo: ppa:ubuntu-mozilla-daily/firefox-aurora
    state: present
  sudo: true
  when: ansible_distribution == 'Ubuntu'
  tags:
    - ppa

- name: Add PPA for Thunderbird Beta Channel.
  apt_repository:
    repo: ppa:mozillateam/thunderbird-next
    state: present
  sudo: true
  when: ansible_distribution == 'Ubuntu'
  tags:
    - ppa

- name: Add PPA for Tor Browser Launcher.
  apt_repository:
    repo: ppa:micahflee/ppa
    state: present
  sudo: true
  when: ansible_distribution == 'Ubuntu'
  tags:
    - ppa

- name: Install graphical packages.
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: common_graphical_packages
  sudo: true
  tags:
    - graphical
    - gui
    - packages

- name: Create Konsole config directories.
  file:
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"
    path: "~{{ username }}/.kde/share/{{ item }}"
  with_items:
    - config
    - apps/konsole

# Configures Konsole dotfiles
- name: Copy konsolerc.
  copy:
    src: konsolerc
    dest: "~{{ username }}/.kde/share/config/konsolerc"
  tags:
    - konsole

- name: Copy default Konsole profile.
  copy:
    src: Shell.profile
    dest: "~{{ username }}/.kde/share/apps/konsole/Shell.profile"
  tags:
    - konsole

  # TODO: All Konsole-related tasks should be writing to the ~/.local
  # directory, since it overrides the defaults in ~/.kde.
- name: Create local Konsole config directory.
  file:
    state: directory
    path: "~{{ username }}/.local/share/konsole"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Copy custom Konsole color scheme.
  copy:
    src: Linux.colorscheme
    # Default location is here, and has a pristine copy.
    # dest: "~{{ username }}/.kde/share/apps/konsole/Linux.colorscheme"
    # Custom location, overrides the default.
    dest: "~{{ username }}/.local/share/konsole/Linux.colorscheme"
  tags:
    - konsole

- name: Create Nitrogen config directory.
  file:
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"
    path: "~{{ username }}/.config/nitrogen"
  tags:
    - nitrogen

- name: Copy Nitrogen config.
  copy:
    dest: "~{{ username }}/.config/nitrogen/{{ item }}"
    src: nitrogen/{{ item }}
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"
  with_items:
    - nitrogen.cfg
    - bg-saved.cfg
  notify: restore nitrogen config
  tags:
    - nitrogen

