---
# Installs packages that require X, so inapproriate
# for headless server environments. See defaults/main.yml
# to override these settings.
- name: Add PPA for Tor Browser Launcher.
  apt_repository:
    repo: ppa:micahflee/ppa
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install graphical packages.
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: "{{ conorsch_env_common_graphical_packages }}"
  become: yes
  tags:
    - graphical
    - gui
    - packages
