---
# Installs packages that require X, so inapproriate
# for headless server environments. See defaults/main.yml
# to override these settings.
- name: Add PPA for Tor Browser Launcher.
  apt_repository:
    repo: ppa:micahflee/ppa
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install graphical packages.
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: common_graphical_packages
  become: yes
  tags:
    - graphical
    - gui
    - packages

- name: Create Nitrogen config directory.
  file:
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"
    path: "~{{ username }}/.config/nitrogen"
  tags:
    - nitrogen

- name: Copy Nitrogen config.
  copy:
    dest: "~{{ username }}/.config/nitrogen/{{ item }}"
    src: nitrogen/{{ item }}
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"
  with_items:
    - nitrogen.cfg
    - bg-saved.cfg
  notify: restore nitrogen config
  tags:
    - nitrogen

