---
# Installs packages that require X, so inapproriate
# for headless server environments. See defaults/main.yml
# to override these settings.

- name: Add PPA for Firefox Developer Edition.
  apt_repository:
    repo: ppa:ubuntu-mozilla-daily/firefox-aurora
    state: present
  sudo: true
  tags:
    - ppa

- name: Add PPA for Thunderbird Beta Channel.
  apt_repository:
    repo: ppa:mozillateam/thunderbird-next
    state: present
  sudo: true
  tags:
    - ppa

- name: Add PPA for Tor Browser Launcher.
  apt_repository:
    repo: ppa:micahflee/ppa
    state: present
  sudo: true
  tags:
    - ppa

- name: Install graphical packages.
  apt:
    pkg: "{{item}}"
    state: installed
    update_cache: yes
  with_items:
    - dunst
    - firefox
    - i3
    - i3lock
    - i3status
    - keepassx
    - konsole
    - nitrogen
    - thunderbird
    - torbrowser-launcher
    - xautolock
    - xcompmgr
  sudo: true
  tags:
    - graphical
    - gui
    - packages

- name: Create Konsole config directories.
  file:
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"
    path: "~{{ username }}/.kde/share/{{ item }}"
  with_items:
    - config
    - apps/konsole

# Configures Konsole dotfiles
- name: Copy konsolerc.
  copy:
    src: konsolerc
    dest: "{{ ansible_env.HOME }}/.kde/share/config/konsolerc"
  tags:
    - konsole

- name: Copy default Konsole profile.
  copy:
    src: Shell.profile
    dest: "{{ ansible_env.HOME }}/.kde/share/apps/konsole/Shell.profile"
  tags:
    - konsole

- name: Copy custom Konsole color scheme.
  copy:
    src: Linux.colorscheme
    dest: "{{ ansible_env.HOME }}/.kde/share/apps/konsole/Linux.colorscheme"
  tags:
    - konsole

- name: Create Nitrogen config directory.
  file:
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"
    path: "{{ ansible_env.HOME }}/.config/nitrogen"
  tags:
    - nitrogen

- name: Copy Nitrogen config.
  copy:
    dest: "{{ ansible_env.HOME }}/.config/nitrogen/{{ item }}"
    src: nitrogen/{{ item }}
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"
  with_items:
    - nitrogen.cfg
    - bg-saved.cfg
  tags:
    - nitrogen

