---
# configures KDE dotfiles
# use custom 'xrandr' module to get screen resolution vars
- name: Get custom xrandr facts.
  action: xrandr
  tags:
    - DEBUG
    - xrandr
# fact should be populated
- debug: var=resolution_as_string

- name: Copy share/config/kcmfonts files to local settings.
  template: src=kcmfonts.j2 dest="~{{ username }}/.kde/share/config/kcmfonts"
  tags:
    - DEBUG
    - xrandr

