---
- include: packages.yml
  tags: packages

- include: users.yml
  tags: users

- include: liquidprompt.yml
  become: yes
  become_user: "{{ username }}"
  tags:
    - dotfiles

- include: rubygems.yml
  become: yes
  become_user: "{{ username }}"
  tags:
    - rubygems
    - gems

- include: graphical_packages.yml
  when: include_graphical_packages
