---
- include: packages.yml

- include: git_config.yml
  tags: git

- include: graphical_packages.yml
  when: conorsch_env_include_graphical_packages == true

- include: nitrogen.yml
  when: conorsch_env_include_graphical_packages == true
  tags: nitrogen

- include: cleanup.yml
