---
- include: packages.yml

- include: users.yml

- include: rubygems.yml

- include: graphical_packages.yml
  when: include_graphical_packages

- include: nitrogen.yml
  when: include_graphical_packages
