--- 
- include: users.yml
- include: packages.yml
- include: homeshick.yml
  tags:
    - dotfiles

- include: liquidprompt.yml
  tags:
    - dotfiles

- include: graphical_packages.yml
  when: include_graphical_packages
  tags:
    - gui

- include: kde_config.yml
  when: include_graphical_packages
  tags:
    - kde
    - gui

