---
- include: users.yml

- include: packages.yml
  tags:
    - packages

- include: dotfiles.yml
  sudo: true
  sudo_user: "{{username}}"
  tags:
    - dotfiles

- include: liquidprompt.yml
  sudo: true
  sudo_user: "{{username}}"
  tags:
    - dotfiles

- include: rubygems.yml
  sudo: true
  sudo_user: "{{username}}"
  tags:
    - rubygems
    - gems

- include: graphical_packages.yml
  when: include_graphical_packages

- include: kde_config.yml
  when: DEBUG
  tags:
    - DEBUG
