--- 
- include: users.yml
- include: packages.yml
- include: homeshick.yml
  sudo: true
  sudo_user: "{{username}}"
  tags:
    - dotfiles
- include: liquidprompt.yml
  sudo: true
  sudo_user: "{{username}}"
  tags:
    - dotfiles
- include: graphical_packages.yml
  when: include_graphical_packages

- include: kde_config.yml
  when: DEBUG
  tags:
    - DEBUG
