---
# Redundant apt task, so the task list is standalone.
- name: Install nitrogen.
  become: yes
  apt:
    name: nitrogen
    state: present

- name: Create nitrogen config directory.
  file:
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0700"
    path: "~{{ username }}/.config/nitrogen"
  tags:
    - nitrogen

- name: Copy nitrogen config.
  copy:
    dest: "~{{ username }}/.config/nitrogen/{{ item }}"
    src: nitrogen/{{ item }}
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"
  with_items:
    - nitrogen.cfg
    - bg-saved.cfg
  notify: restore nitrogen config
  tags:
    - nitrogen

