---
# Redundant apt task, so the task list is standalone.
- name: Install nitrogen.
  become: yes
  apt:
    name: nitrogen
    state: present

- name: Create nitrogen config directory.
  file:
    state: directory
    owner: "{{ conorsch_env_username }}"
    group: "{{ conorsch_env_username }}"
    mode: "0700"
    path: "~{{ conorsch_env_username }}/.config/nitrogen"
  register: nitrogen_config_dir_result
  tags:
    - nitrogen

- name: Copy nitrogen config.
  copy:
    dest: "~{{ conorsch_env_username }}/.config/nitrogen/{{ item }}"
    src: nitrogen/{{ item }}
    owner: "{{ conorsch_env_username }}"
    group: "{{ conorsch_env_username }}"
    mode: "0600"
  with_items:
    - nitrogen.cfg
    - bg-saved.cfg
  notify: restore nitrogen config
  # The nitrogen config file stores info on desktop backgrounds. The file
  # structure varies significantly if multiple monitors are attached, which
  # makes smart handling difficult in the context of this role. By default,
  # just install the package and create the config directory, but don't clobber.
  when: nitrogen_config_dir_result.changed == true
  tags:
    - nitrogen

