---
# Redundant apt task, so the task list is standalone.
- name: Install nitrogen.
  become: yes
  apt:
    name: nitrogen
    state: present

- name: Create nitrogen config directory.
  become: no
  file:
    state: directory
    owner: "{{ conorsch_env_username }}"
    group: "{{ conorsch_env_username }}"
    mode: "0700"
    path: "~{{ conorsch_env_username }}/.config/nitrogen"
  register: nitrogen_config_dir_result

- name: Copy nitrogen config.
  copy:
    dest: "~{{ conorsch_env_username }}/.config/nitrogen/{{ item }}"
    src: nitrogen/{{ item }}
    owner: "{{ conorsch_env_username }}"
    group: "{{ conorsch_env_username }}"
    mode: "0600"
  with_items:
    - nitrogen.cfg
    - bg-saved.cfg
  notify: restore nitrogen config
  # The nitrogen config file stores info on desktop backgrounds. The file
  # structure varies significantly if multiple monitors are attached, which
  # makes smart handling difficult. Disabling the configs to allow drift on hosts.
  when: false

- name: Clone desktop pictures repository.
  git:
    repo: "https://github.com/{{ conorsch_env_github_username }}/desktoppics"
    dest: "~{{ conorsch_env_username }}/.desktoppics"
