---
- name: Install common packages.
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ conorsch_env_common_packages }}"
  become: yes
  tags:
    - packages

- name: Install pip packages.
  pip:
    state: latest
    name: "{{ item }}"
    extra_args: "--user"
  # Joining the package list into a consolidated item makes
  # the pip task much, much faster: 3s, down from 20s with 10 packages.
  with_items: "{{ conorsch_env_pip_packages | join(' ') }}"
  # Running inside a virtualenv, the --user flag will cause the call to fail.
  when: "'VIRTUAL_ENV' not in ansible_env and
        conorsch_env_pip_packages != []"
  tags:
    - pip
