---
- name: Include OS-specific vars.
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install favorite packages.
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: favorite_packages
  sudo: true
  tags:
    - packages

- name: Remove system python-pip on Debian.
  apt:
    name: python-pip
    state: absent
  sudo: true
  when: 'ansible_distribution == "Debian"'

- name: easy_install pip on Debian
  easy_install:
    name: pip
  sudo: true
  when: 'ansible_distribution == "Debian"'

  # Without requests[security], under Ubuntu,
  # libcurl3 throws insecure SSL warnings.
  # Under Debian, though, trying to install requests[security]
  # with --user via Ansible
- name: Install requests[security] on Ubuntu.
  pip:
    state: latest
    name: requests[security]
  when: ansible_distribution == "Ubuntu"
  tags:
    - pip

- name: Install pip packages.
  pip:
    state: latest
    name: "{{ item }}"
  with_items: pip_packages
  tags:
    - pip
