---
- name: install favorite packages
  apt:
    pkg: "{{item}}"
    state: installed
    update_cache: yes
  with_items:
    - build-essential
    - git
    - htop
    - ipython
    - python-dev
    - rubygems
    - rubygems-integration
    - tree
    - vim
  sudo: true
  tags:
    - packages

- name: remove system python-pip
  apt:
    name: python-pip
    state: absent

- name: easy_install pip
  easy_install:
    name: pip

  # Without requests[security], under Ubuntu,
  # libcurl3 throws insecure SSL warnings.
  # Under Debian, though, trying to install requests[security]
  # with --user via Ansible
- name: install requests[security] on Ubuntu
  pip:
    state: latest
    name: requests[security]
  when: 'ansible_distribution == "Ubuntu"'
  tags:
    - pip

- name: install pip packages via pip
  pip:
    state: latest
    name: "{{item}}"
    extra_args: "--user"
  sudo: true
  sudo_user: "{{ username }}"
  with_items: pip_packages
  tags:
    - pip
