---
- name: Include OS-specific vars.
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install common packages.
  apt:
    pkg: "{{ item }}"
    state: installed
    update_cache: yes
  with_items: common_packages
  register: common_apt_packages_result
  sudo: true
  tags:
    - packages

- name: Install pip packages.
  pip:
    state: latest
    name: "{{ item }}"
    extra_args: "--user"
  # Joining the package list into a consolidated item makes
  # the pip task much, much faster: 3s, down from 20s with 10 packages.
  with_items: pip_packages | join(' ')
  tags:
    - pip
