---
- name: install favorite packages
  apt:
    pkg: "{{item}}"
    state: installed
    update_cache: yes
  with_items:
    - git
    - vim
    - tree
    - ipython
    - python-dev
    - python-pip
    - build-essential
  sudo: true
  tags:
    - packages

- name: install pip packages via pip
  pip:
    state: latest
    name: "{{item}}"
    extra_args: "--user"
  sudo: false
  with_items: pip_packages
  tags:
    - pip
