---
- name: install favorite packages
  apt:
    pkg: "{{item}}"
    state: installed
    update_cache: yes
  with_items:
    - build-essential
    - git
    - htop
    - ipython
    - python-dev
    - rubygems-integration
    - tree
    - vim
  sudo: true
  tags:
    - packages

- name: remove system package python-pip
  apt:
    name: python-pip
    state: absent

- name: remove system package python-pip
  easy_install:
    name: pip

- name: install pip packages via pip
  pip:
    state: latest
    name: "{{item}}"
    extra_args: "--user"
  sudo: true
  sudo_user: "{{ username }}"
  with_items: pip_packages
  tags:
    - pip
