---
- name: install favorite packages
  apt:
    pkg: "{{item}}"
    state: installed
    update_cache: yes
  with_items:
    - git
    - vim
    - tree
    - ipython
    - python-dev
    - build-essential
  sudo: true
  tags:
    - packages

