---
# create user account and add ssh keys via github
- name: Fallback from root to normal user for env config.
  set_fact:
    username: "{{ lookup('pipe', 'whoami') }}"
  when: ansible_user_id == "root"

- name: Create group for user.
  group:
    name: "{{ username }}"
    state: present
  become: yes

- name: Create user.
  user:
    name: "{{ username }}"
    shell: "{{ default_shell }}"
  become: yes

- name: Add authorized SSH keys for user.
  authorized_key:
    user: "{{ username }}"
    key: "{{ github_key_url }}"
  tags:
    - ssh

- name: Add passwordless sudo to cloud hosts.
  template:
    src: sudoers
    dest: /etc/sudoers.d/{{ username }}
    owner: root
    group: root
    mode: "0644"
  become: yes
  when: "'personal' not in group_names"
  tags:
    - sudo

- name: Remove passwordless sudo from personal machines.
  file:
    path: /etc/sudoers.d/{{ username }}
    state: absent
  become: yes
  when: "'personal' in group_names"
  tags:
    - sudo

- name: Tighten up permissions on home directory.
  file:
    state: directory
    path: "/home/{{ username }}"
    mode: "0750"
    owner: "{{ username }}"
    group: "{{ username }}"
  become: no
