---
# create user account and add ssh keys via github
- name: ensure group exists
  group: name={{username}} state=present
  sudo: true

- name: ensure user exists
  user:
    name: "{{username}}"
    groups: "{{username}}"
    append: yes
    shell: "{{default_shell}}"
  sudo: true

- name: add ssh key for user
  authorized_key:
    user: "{{username}}"
    key: "{{github_key_url}}"
  tags:
    - ssh

- name: grant passwordless sudo
  template:
    src: sudoers
    dest: /etc/sudoers.d/{{username}}
    owner: root
    group: root
    mode: "0644"
